### ISSUE TITLE
Google Drive Support

### ISSUE THREAD

**Issue by qjhart** [CSTARS/ceres-maps#5]
Can we reenable Google Drive support in the default maps viewer.  It's a very convenient sharing mechanism.

**Comment by jrmerz** [comment]
Support is there, you just need to provide the config file with the API key.  You want to enable it for the http://cstars.github.io/ceres-maps/ url?  And if so, what Google API account to do want to use or do you want to create a new one?

**Comment by qjhart** [comment]
What's your feeling on that? @jrmerz I guess my question is mostly about ownership.  Since you most recently had the pain and suffering of transferring ownereship, that's why I was asking.  What would be ideal is to attach Google APIs to something like the Googl+ pages (bioinformatics) some seperate entity, like that, that doesn't have it's own gmail account.  In the absence of that, is it worth setting up some shared framework or just attching it to my account?

**Comment by jrmerz** [comment]
Not sure... that's why I was asking you.
